name: protein-like_msm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab
  - numpy
  - matplotlib
  - rich
  - tqdm
  - scipy
  - deeptime
  - MDAnalysis
  - pip:
    - ray
